spring:
  application:
    name: linghuzhiyan-experiment-service

  # Spring Cloud Config (可选加载)
  config:
#    import: optional:configserver:http://config:config123@localhost:8888

    import: optional:configserver:http://config:config123@config-server:8888
