spring:
  application:
    name: linghuzhiyan-user-service
  config:
#    import: optional:configserver:http://config:config123@localhost:8888
    import: optional:configserver:http://config:config123@config-server:8888
