services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-01-11T07-46-16Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/minio/data:/data

  discovery:
    build:
      context: .
      dockerfile: ./linghuzhiyan-discovery-server/Dockerfile
    container_name: discovery
    ports:
      - "8761:8761"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"

  config:
    build:
      context: .
      dockerfile: ./linghuzhiyan-config-server/Dockerfile
    container_name: config
    depends_on:
      - discovery
    ports:
      - "8888:8888"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://admin:admin123@discovery:8761/eureka/"
    volumes:
      - ./config-repo:/app/config-repo:ro

  gateway:
    build:
      context: .
      dockerfile: ./linghuzhiyan-gateway/Dockerfile
    container_name: gateway
    depends_on:
      - config
      - discovery
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:config123@config:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://admin:admin123@discovery:8761/eureka/"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"

  auth:
    build:
      context: .
      dockerfile: ./linghuzhiyan-auth-service/Dockerfile
    container_name: auth
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      config:
        condition: service_started
      discovery:
        condition: service_started
    ports:
      - "8084:8084"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:config123@config:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://admin:admin123@discovery:8761/eureka/"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"

  user:
    build:
      context: .
      dockerfile: ./linghuzhiyan-user-service/Dockerfile
    container_name: user
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      config:
        condition: service_started
      discovery:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:config123@config:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://admin:admin123@discovery:8761/eureka/"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"

  experiment:
    build:
      context: .
      dockerfile: ./linghuzhiyan-experiment-service/Dockerfile
    container_name: experiment
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      config:
        condition: service_started
      discovery:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:config123@config:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://admin:admin123@discovery:8761/eureka/"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"

  resource:
    build:
      context: .
      dockerfile: ./linghuzhiyan-resource-service/Dockerfile
    container_name: resource
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      config:
        condition: service_started
      discovery:
        condition: service_started
    ports:
      - "8086:8086"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:config123@config:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://admin:admin123@discovery:8761/eureka/"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"

  message:
    build:
      context: .
      dockerfile: ./linghuzhiyan-message-service/Dockerfile
    container_name: message
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      config:
        condition: service_started
      discovery:
        condition: service_started
    ports:
      - "8085:8085"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:config123@config:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://admin:admin123@discovery:8761/eureka/"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"

  discussion:
    build:
      context: .
      dockerfile: ./linghuzhiyan-discussion-service/Dockerfile
    container_name: discussion
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      config:
        condition: service_started
      discovery:
        condition: service_started
    ports:
      - "8087:8087"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:config123@config:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://admin:admin123@discovery:8761/eureka/"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"

networks:
  default:
    name: linghuzhiyan-net
    driver: bridge
