spring:
  application:
    name: linghuzhiyan-gateway
  config:
    import: optional:configserver:http://config:config123@config-server:8888

# # JWT 备用配置（防止配置服务器不可用）
# jwt:
#   secret: ${JWT_SECRET:linghuzhiyan-used-secret-key-must-be-at-least-32-characters-long-for-security}
#   tokenHeader: ${JWT_TOKEN_HEADER:Authorization}
#   tokenHead: ${JWT_TOKEN_HEAD:Bearer}