apiVersion: v1
kind: ConfigMap
metadata:
  name: config-repo
  namespace: linghuzhiyan
data:
  application.yml: |
    # 通用配置 - 所有服务共享（K8s环境）
    spring:
      datasource:
        # 数据库连接池配置
        hikari:
          maximum-pool-size: 20
          minimum-idle: 5
          idle-timeout: 300000
          max-lifetime: 1800000
          connection-timeout: 20000
          validation-timeout: 5000
          
      # JPA 配置
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
            
      # Redis 配置 - K8s环境
      redis:
        host: ${SPRING_REDIS_HOST:redis}
        port: ${SPRING_REDIS_PORT:6379}
        timeout: 2000ms
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: -1ms

    # MongoDB 配置 - K8s环境
    spring.data.mongodb:
      host: mongo
      port: 27017
      database: linghuzhiyan
      username: root
      password: example
      authentication-database: admin

    # MinIO 配置 - K8s环境
    minio:
      endpoint: http://minio:9000
      accessKey: minioadmin
      secretKey: minioadmin
      bucketName: linghuzhiyan

    # Eureka 通用配置 - K8s环境
    eureka:
      client:
        service-url:
          defaultZone: http://admin:admin123@discovery-server:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 30

    # 通用监控配置
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,env
      endpoint:
        health:
          show-details: always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: linghuzhiyan
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: linghuzhiyan-config-server:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m"
        - name: SPRING_PROFILES_ACTIVE
          value: "native"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://admin:admin123@discovery-server:8761/eureka/"
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config-repo
          mountPath: /app/config-repo
          readOnly: true
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config-repo
        configMap:
          name: config-repo
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: linghuzhiyan
  labels:
    app: config-server
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: config-server
