apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: linghuzhiyan
  labels:
    app: message-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: linghuzhiyan-message-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m"
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MINIO_ENDPOINT
          value: "http://minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config:config123@config-server:8888"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://admin:admin123@discovery-server:8761/eureka/"
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 8085
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: linghuzhiyan
  labels:
    app: message-service
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: message-service
