apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: linghuzhiyan
data:
  MYSQL_ROOT_PASSWORD: "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: linghuzhiyan
data:
  001-init-databases.sql: |
    -- Initialize databases for services (MySQL 8 default collation)
    CREATE DATABASE IF NOT EXISTS linghuzhiyan_auth
      DEFAULT CHARACTER SET utf8mb4
      DEFAULT COLLATE utf8mb4_0900_ai_ci;

    CREATE DATABASE IF NOT EXISTS linghuzhiyan_user
      DEFAULT CHARACTER SET utf8mb4
      DEFAULT COLLATE utf8mb4_0900_ai_ci;

    -- Message service database
    CREATE DATABASE IF NOT EXISTS linghuzhiyan_message
      DEFAULT CHARACTER SET utf8mb4
      DEFAULT COLLATE utf8mb4_0900_ai_ci;

    -- Resource service database
    CREATE DATABASE IF NOT EXISTS linghuzhiyan_resource
      DEFAULT CHARACTER SET utf8mb4
      DEFAULT COLLATE utf8mb4_0900_ai_ci;

    -- Discussion service database
    CREATE DATABASE IF NOT EXISTS linghuzhiyan_discussion
      DEFAULT CHARACTER SET utf8mb4
      DEFAULT COLLATE utf8mb4_0900_ai_ci;

    -- Experiment service database
    CREATE DATABASE IF NOT EXISTS linghuzhiyan_experiment
      DEFAULT CHARACTER SET utf8mb4
      DEFAULT COLLATE utf8mb4_0900_ai_ci;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: linghuzhiyan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: linghuzhiyan
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_ROOT_PASSWORD
        args:
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: linghuzhiyan
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
