apiVersion: v1
kind: Namespace
metadata:
  name: linghuzhiyan
  labels:
    name: linghuzhiyan
    app.kubernetes.io/name: linghuzhiyan
    app.kubernetes.io/part-of: linghuzhiyan-microservices
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: linghuzhiyan-quota
  namespace: linghuzhiyan
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: linghuzhiyan-limits
  namespace: linghuzhiyan
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
