spring:
  application:
    name: linghuzhiyan-auth-service
  config:
    import: optional:configserver:http://config:config123@config-server:8888
    # 本地测试用
#    import: optional:configserver:http://config:config123@localhost:8888
