# 网关服务配置
server:
  port: 8080

spring:
  application:
    name: linghuzhiyan-gateway
    
  cloud:
    gateway:
      # 全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:8080"
              - "http://localhost:8888"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      
      # 路由配置
      routes:
        # 认证服务路由
        - id: auth-service
          uri: lb://linghuzhiyan-auth-service
          predicates:
            - Path=/api/auth/**
#          filters:
#            - StripPrefix=2

        # 认证服务内部路由
        - id: auth-service-internal
          uri: lb://linghuzhiyan-auth-service
          predicates:
            - Path=/api/internal/auth/**
#          filters:
#            - StripPrefix=3

        # 用户服务路由
        - id: user-service
          uri: lb://linghuzhiyan-user-service
          predicates:
            - Path=/api/users/**
#          filters:
#            - StripPrefix=2

        # 用户服务内部路由
        - id: user-service-internal
          uri: lb://linghuzhiyan-user-service
          predicates:
            - Path=/api/internal/users/**
#          filters:
#            - StripPrefix=3
            
        # 实验服务路由
        - id: experiment-service
          uri: lb://linghuzhiyan-experiment-service
          predicates:
            - Path=/api/experiments/**,/api/questions/**,/api/student/experiments/**
#          filters:
#            - StripPrefix=2

        # 实验服务内部路由
        - id: experiment-service-internal
          uri: lb://linghuzhiyan-experiment-service
          predicates:
            - Path=/api/internal/experiments/**
#          filters:
#            - StripPrefix=3
            
        # 资源服务路由
        - id: resource-service
          uri: lb://linghuzhiyan-resource-service
          predicates:
            - Path=/api/resources/**
#          filters:
#            - StripPrefix=2
            
        # 讨论服务路由
        - id: discussion-service
          uri: lb://linghuzhiyan-discussion-service
          predicates:
            - Path=/api/discussions/**,/api/comments/**
#          filters:
#            - StripPrefix=2
            
        # 消息服务路由
        - id: message-service
          uri: lb://linghuzhiyan-message-service
          predicates:
            - Path=/api/messages/**,/api/announcements/**
#          filters:
#            - StripPrefix=2
            
        # Swagger文档路由
        - id: user-service-swagger
          uri: lb://linghuzhiyan-user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - StripPrefix=1
            
        - id: auth-service-swagger
          uri: lb://linghuzhiyan-auth-service
          predicates:
            - Path=/auth-service/v3/api-docs
          filters:
            - StripPrefix=1
            
        - id: experiment-service-swagger
          uri: lb://linghuzhiyan-experiment-service
          predicates:
            - Path=/experiment-service/v3/api-docs
          filters:
            - StripPrefix=1
            
        - id: resource-service-swagger
          uri: lb://linghuzhiyan-resource-service
          predicates:
            - Path=/resource-service/v3/api-docs
          filters:
            - StripPrefix=1
            
        - id: discussion-service-swagger
          uri: lb://linghuzhiyan-discussion-service
          predicates:
            - Path=/discussion-service/v3/api-docs
          filters:
            - StripPrefix=1
            
        - id: message-service-swagger
          uri: lb://linghuzhiyan-message-service
          predicates:
            - Path=/message-service/v3/api-docs
          filters:
            - StripPrefix=1

# SpringDoc配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /user-service/v3/api-docs
        name: "用户服务"
      - url: /auth-service/v3/api-docs
        name: "认证服务"
      - url: /experiment-service/v3/api-docs
        name: "实验服务"
      - url: /resource-service/v3/api-docs
        name: "资源服务"
      - url: /message-service/v3/api-docs
        name: "消息服务"
      - url: /discussion-service/v3/api-docs
        name: "讨论服务"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,filters
  endpoint:
    gateway:
      enabled: true
  server:
    port: 8081

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.linghu.gateway: DEBUG
