# 网关服务配置
server:
  port: 8080

spring:
  application:
    name: linghuzhiyan-gateway
    
  cloud:
    gateway:
      # 全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:8080"
              - "http://localhost:8888"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      
      # 路由配置
      routes:
        # 认证服务路由
        - id: auth-service
          uri: lb://linghuzhiyan-auth-service
          predicates:
            - Path=/api/auth/**
          

        # 认证服务内部路由
        - id: auth-service-internal
          uri: lb://linghuzhiyan-auth-service
          predicates:
            - Path=/api/internal/auth/**
          filters:
            - StripPrefix=3

        # 用户服务路由
        - id: user-service
          uri: lb://linghuzhiyan-user-service
          predicates:
            - Path=/api/users/**
          

        # 用户服务内部路由
        - id: user-service-internal
          uri: lb://linghuzhiyan-user-service
          predicates:
            - Path=/api/internal/users/**
          filters:
            - StripPrefix=3
            
        # 实验服务路由
        - id: experiment-service
          uri: lb://linghuzhiyan-experiment-service
          predicates:
            - Path=/api/experiments/**
          filters:
            - StripPrefix=1

        # 实验服务内部路由
        - id: experiment-service-internal
          uri: lb://linghuzhiyan-experiment-service
          predicates:
            - Path=/api/internal/experiments/**
          filters:
            - StripPrefix=3
            
        # 资源服务路由
        - id: resource-service
          uri: lb://linghuzhiyan-resource-service
          predicates:
            - Path=/api/resources/**
          filters:
            - StripPrefix=1
            
        # 讨论服务路由
        - id: discussion-service
          uri: lb://linghuzhiyan-discussion-service
          predicates:
            - Path=/api/discussions/**
          filters:
            - StripPrefix=1
            
        # 消息服务路由
        - id: message-service
          uri: lb://linghuzhiyan-message-service
          predicates:
            - Path=/api/messages/**
          filters:
            - StripPrefix=1

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,filters
  endpoint:
    gateway:
      enabled: true
  server:
    port: 8081

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.linghu.gateway: DEBUG
