# 监控服务配置
server:
  port: 8090

spring:
  application:
    name: linghuzhiyan-monitor-service
    
  # Spring Boot Admin 配置
  boot:
    admin:
      server:
        ui:
          title: "灵狐智验监控中心"
          brand: "灵狐智验"
      client:
        url: http://localhost:8090
        instance:
          service-url: http://localhost:8090
          
  # 安全配置
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
      roles: ADMIN

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    org.linghu.monitor: DEBUG
