server:
  port: 8888

spring:
  application:
    name: linghuzhiyan-config-server
    
  # 配置中心配置 - K8s环境
  cloud:
    config:
      server:
        # 使用本地文件系统配置（从ConfigMap挂载）
        native:
          search-locations: file:/app/config-repo,classpath:/config-repo
        # 激活native profile
        default-profile: native
          
  # 安全配置
  security:
    user:
      name: config
      password: config123
      roles: ADMIN

# Eureka 客户端配置 - K8s环境
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://admin:admin123@discovery-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Actuator 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    org.springframework.cloud.config: INFO
    org.springframework.cloud.netflix.eureka: INFO
