apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: discovery-server:j21
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: JAVA_OPTS
              value: "-Dserver.address=0.0.0.0"
          readinessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: LoadBalancer
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
