apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-env
data:
  # 数据源配置（从 .env.development 映射）
  DB_HOST: "10.128.55.225"
  DB_PORT: "3306"
  SPRING_DATASOURCE_URL: "jdbc:mysql://10.128.55.225:3306/linghuzhiyan?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_PROFILES_ACTIVE: "local"
  # Eureka 集群内地址（Spring 环境变量映射：eureka.client.serviceUrl.defaultZone / eureka.client.service-url.defaultZone）
  # 同时提供两种键名以兼容 camelCase 与连字符风格
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://admin:admin123@discovery-server:8761/eureka/"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://admin:admin123@discovery-server:8761/eureka/"
  SPRING_CLOUD_CONFIG_ENABLED: "false"

  # MinIO 配置（非敏感项）
  MINIO_ENDPOINT: "http://10.128.55.225:9000"
  MINIO_BUCKETNAME: "linghuzhiyan"

  # 兼容命名（可选）
  MINIO_BUCKET_NAME: "linghuzhiyan"
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "lop*123456lop*"

---
apiVersion: v1
kind: Secret
metadata:
  name: user-minio-secret
type: Opaque
stringData:
  # MinIO 访问密钥（敏感项）
  MINIO_ACCESSKEY: "keyan"
  MINIO_SECRETKEY: "lop*123456lop*"
  # 兼容命名（可选）
  MINIO_ACCESS_KEY: "keyan"
  MINIO_SECRET_KEY: "lop*123456lop*"
