name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  # packages: write  # Uncomment if you plan to push images to GHCR

jobs:
  build-java:
    name: Build (Maven)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Temurin Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Maven Clean Verify
        run: mvn -B -ntp clean verify

      - name: Upload JAR Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ github.sha }}
          if-no-files-found: warn
          path: |
            **/target/*.jar
            !**/*-sources.jar
            !**/*-javadoc.jar

  docker-build:
    name: Docker Build (no push)
    runs-on: ubuntu-latest
    needs: build-java
    strategy:
      fail-fast: false
      matrix:
        svc:
          - { name: 'discovery-server', path: 'linghuzhiyan-discovery-server' }
          - { name: 'config-server',    path: 'linghuzhiyan-config-server' }
          - { name: 'gateway',          path: 'linghuzhiyan-gateway' }
          - { name: 'monitor-service',  path: 'linghuzhiyan-monitor-service' }
          - { name: 'auth-service',     path: 'linghuzhiyan-auth-service' }
          - { name: 'user-service',     path: 'linghuzhiyan-user-service' }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # If you want to push to GHCR, uncomment login and set permissions packages: write above
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image ${{ matrix.svc.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.svc.path }}
          file: ${{ matrix.svc.path }}/Dockerfile
          push: false
          tags: ${{ matrix.svc.name }}:ci-${{ github.sha }}
